CREATE TABLE BOOK
(
  BOOK_ID      NUMBER        NOT NULL,
  TITLE        NVARCHAR2(50) NOT NULL,
  RELEASE_DATE TIMESTAMP     NOT NULL,
  DESCRIPTION  CLOB,
  GENRE        NVARCHAR2(50) NOT NULL,
  BESTSELLER   NUMBER(1, 0),
  PRICE        NUMBER        NOT NULL,
  AVAILABILITY NUMBER(1, 0),
  DISCOUNT     NUMBER(1, 0),
  CONSTRAINT BOOK_PK PRIMARY KEY (BOOK_ID)
);