CREATE TABLE ORDER_BOOK(
    ORDER_ID NUMBER NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    STATUS NVARCHAR2(50) NOT NULL,
    DELIVERY_ADDRESS NVARCHAR2(50) NOT NULL,
    COUNT NUMBER NOT NULL,
    PRICE NUMBER NOT NULL,
    CLIENT NUMBER,
    CONSTRAINT ORDER_PK PRIMARY KEY (ORDER_ID),
    CONSTRAINT CLIENT_FK FOREIGN KEY (CLIENT) REFERENCES CLIENT(CLIENT_ID)
);