CREATE TABLE CLIENT(
    CLIENT_ID NUMBER NOT NULL,
    NAME NVARCHAR2(50) NOT NULL,
    AGE NUMBER NOT NULL,
    PHONE_NUMBER NVARCHAR2(50) NOT NULL,
    EMAIL NVARCHAR2(50),
    CONSTRAINT CLIENT_PK PRIMARY KEY (CLIENT_ID)
);