CREATE TABLE BOOK(
    BOOK_ID INT NOT NULL,
    TITLE NVARCHAR2(50) NOT NULL,
    RELEASE_DATE DATE NOT NULL,
    DESCRIPTION CLOB,
    GENRE NVARCHAR2(50) NOT NULL,
    BESTSELLER BOOLEAN NOT NULL,
    PRICE INT NOT NULL,
    AVAILABILITY BOOLEAN NOT NULL,
    DISCOUNT BOOLEAN NOT NULL,
    PRIMARY KEY (BOOK_ID)
);