CREATE TABLE CLIENT(
    CLIENT_ID INT NOT NULL,
    NAME NVARCHAR2(50) NOT NULL,
    AGE INT NOT NULL,
    PHONE_NUMBER NVARCHAR2(50) NOT NULL,
    EMAIL NVARCHAR2(50),
    PRIMARY KEY (CLIENT_ID)
);